version: '3.8'

services:
  localstack:
    network_mode: bridge
    build:
      context: .
    container_name: localstack_example
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,iam
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_HOST=localstack
      - LAMBDA_EXECUTION=local
    volumes:
      - ./localSetup.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./admin-policy.json:/opt/code/localstack/admin-policy.json
      - /var/run/docker.sock:/var/run/docker.sock
